### ISSUE TITLE
Aadhar Secure QR code getting data mismatching

### ISSUE THREAD

**Issue by ravitejac** [Tanmoy741127/pyaadhaar#3]
Hi tanmoy,

I am trying with your script for aadhar secure QR code getting data mismatching as follows:

{'email_mobile_status': 'V', 'referenceid': '2', 'name': '12345678', 'dob': 'test', 'gender': 'dd-mm-yyyy', 'careof': 'M', 'district': 's/o test abc', 'landmark': 'Hyderabad', 'house': '', 'location': '1-4/232', 'pincode': '', 'postoffice': 'xxx20', 'state': '', 'street': 'Andhra Pradesh', 'subdistrict': 'gachibowli', 'vtc': '', 'adhaar_last_4_digit': '2', 'adhaar_last_digit': '2'}

I am getting data wrongly mapped. Can you please suggest and help me out how to solve this issue?

Thanks,
Ravi

**Comment by Tanmoy741127** [comment]
Can  you tell me specifically where dogs mismatching??

**Comment by ravitejac** [comment]
Hi tanmoy,

Please check the below response. If you observe in dob it is coming as name, reference id coming as name and so on...
Data is wrongly mapped I meant to say.

{'email_mobile_status': 'V', 'referenceid': '2', 'name': '12345678', 'dob': 'test', 'gender': 'dd-mm-yyyy', 'careof': 'M', 'district': 's/o test abc', 'landmark': 'Hyderabad', 'house': '', 'location': '1-4/232', 'pincode': '', 'postoffice': 'xxx20', 'state': '', 'street': 'Andhra Pradesh', 'subdistrict': 'gachibowli', 'vtc': '', 'adhaar_last_4_digit': '2', 'adhaar_last_digit': '2'}

Source code:
import cv2
from pyzbar.pyzbar import decode
from pyaadhaar.decode import AadhaarSecureQr
from pyaadhaar.utils import isSecureQr
img = cv2.imread('image-011.png')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

code = decode(gray)
qrData = code[0].data
isSecureQR = (isSecureQr(qrData))
if isSecureQR:
    secure_qr = AadhaarSecureQr(int(qrData))
    decoded_secure_qr_data = secure_qr.decodeddata()
    print(decoded_secure_qr_data)

Thanks,
Ravi

**Comment by ravitejac** [comment]
Are you able to understand above issue which I messaged earlier?

**Comment by Tanmoy741127** [comment]
I am busy. As soon as i got time, i will reply.
ᐧ

**Comment by Tanmoy741127** [comment]
Ok i need to check, if there is any changes in latest encryption

Thanks & regards
Tanmoy Sarkar
ᐧ

**Comment by Arkajit-Datta** [comment]
I faced the exact same problem and have submitted a PR for the same. The problem has occurred due to a change in the format of the data being stored in the QR Code. UIDAI is apparently saving a keyword - "V2" in the beginning (this was discovered while debugging the decompressed string). Please refer to the PR, will be happy to hear from you!

**Comment by Tanmoy741127** [comment]
Closing the issue.
