### ISSUE TITLE
Bugs in MobileRegistered and EmailRegistered Methods

### ISSUE THREAD

**Issue by Arkajit-Datta** [Tanmoy741127/pyaadhaar#5]
**Describe the bug**
The check for the presence of email and mobile seems to be wrong in the methods. When email_mobile_status is 3 or 2, in that case, the function should return mobile is registered, though it is referring to 3 or 1. similar case with the email registered method too. 

**Expected behaviour**
The functions should return legitimate True values when email and mobile are present, Though we are receiving erroneous returns

**Screenshots**
![image](https://user-images.githubusercontent.com/61142632/195971972-1381d8e8-4408-4cfc-bb2b-e23ff1cf0b39.png)

**Comment by Arkajit-Datta** [comment]
**Posting for Reference**
![image](https://user-images.githubusercontent.com/61142632/195972103-3ba32640-b72e-4f19-9388-70791723fa0d.png)

**Comment by Arkajit-Datta** [comment]
Hey Tanmoy, 
I have raised a PR in regard to a fix for this issue. Please have a look.

Thanks and Regards, 
Arkajit Datta

**Comment by Tanmoy741127** [comment]
Can you please share the latest schema published by UIDAI

**Comment by Arkajit-Datta** [comment]
sure, lemme upload the latest schema! 
sharing the link -->
https://uidai.gov.in/images/resource/User_manulal_QR_Code_15032019.pdf

**Comment by Tanmoy741127** [comment]
Fixed in PR #6
